[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "email-validator>=2.2.0",
    "flask>=3.1.1",
    "flask-sqlalchemy>=3.1.1",
    "graphviz>=0.21",
    "gunicorn>=23.0.0",
    "matplotlib>=3.10.3",
    "numpy>=2.3.2",
    "pandas>=2.3.1",
    "pillow>=11.3.0",
    "pm4py>=2.7.16",
    "psycopg2-binary>=2.9.10",
    "river>=0.22.0",
    "scikit-learn>=1.7.1",
    "sqlalchemy>=2.0.42",
    "tqdm>=4.67.1",
    "werkzeug>=3.1.3",
]
